Oppsamlingsheat for endringer siden 2019

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -153,7 +153,7 @@ repo() {
 	url="$base_url/$tree/$branch$relative_path"
 
 
-	echo "Calling $(type open) for $url"
+	echo "Calling $(type xdg-open) for $url"
 
 	xdg-open "$url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
 }
@@ -221,10 +221,19 @@ random() {
 function cat() {
 if [ -f $1 ] ; then
 		case $1 in
-			*.md) mdcat $1 | bat ;;
-			*) bat $1 ;;
+			*.md) mdcat $1 | batcat ;;
+			*.json) fx $1 ;;
+			*) batcat $1 ;;
 		esac
 	else
 		echo "'$1' is not a valid file"
 	fi
+}
+
+# view npm package in browser
+viewpackage() {
+	package_name=$1
+	package_url=$(command npm info $package_name homepage) 2>/dev/null
+
+	xdg-open "$package_url" &> /dev/null || (echo "Using $(type open) to open URL failed." && exit 1);
 }
